### ISSUE TITLE
PowerPoint_R_Part_1.R - mso.txt required before being sourced

### ISSUE THREAD

**Issue by ojessen** [asifsalam/PowerPoint_from_R#1]
Currently, mso.txt is being required by slide1 <- presentation[["Slides"]]$Add(1,ms$ppLayoutBlank)
but only loaded in the next step.

**Comment by ojessen** [comment]
BTW, thanks for this great tutorial.

**Comment by asifsalam** [comment]
Yes, my mistake.  I've changed the code and tutorial to use the value (12) explicitly, before the enumerated constants are read in.  Should result in a blank slide. 
Thanks Owe.
